### ISSUE TITLE
Import existing GNUSocial posts

### ISSUE THREAD

**Issue by faulteh** [taslug/taslug.github.io#1]
Use the RSS importer would probably be the easiest.

Perhaps put them in a single blog category

**Comment by jerrykan** [comment]
Seems like the activity stream is the easiest place to pull the posts from (https://taslug.org.au/api/statuses/user_timeline/2.as).

I've coded up an initial scraper, but it still needs a bit of work.

**Comment by faulteh** [comment]
RSS Feed of public timeline
https://taslug.org.au/api/statuses/public_timeline.rss

Or for individual users, eg taslug user:
https://taslug.org.au/api/statuses/user_timeline/2.rss

That way you can use the python feedparser module to parse it up.

I just tried to run the Jekyll RSS importer but it failed - basically it makes filenames from the post title, but looking at the above RSS, the entire post is in the title with all the markdown making the filename too long. 

Most of the taslug user's post titles start with:
> taslug: ##Hobart August 18th Meeting - High Performance Computing (HPC) ....
but it looks like the newline formatting from the markdown has been removed there

The Activity stream looks good as you get the HTML but you need to figure out a "post title" from that. Almost all taslug posts start with ##Hobart or ##Launceston  (so <h2> or you could strip the html and take the first 150 chars or something.

**Comment by faulteh** [comment]
Put the scraper in a scripts directory in the repo when you're ready to commit

**Comment by faulteh** [comment]
The other option is I could dump the SQL and send it over - perhaps one of the fields in the database has kept the markdown intact

**Comment by faulteh** [comment]
Wordpress import is done.. check out how it has done the categories since it's yaml front matter

Also, instead can we use the "TasLUG South" and "TasLUG North" categories instead of hobart/launceston as that's what the wordpress categories were.
